### ISSUE TITLE
Reading XML emails sometimes contains data not in original email?

### ISSUE THREAD

**Issue by SpyridonZ** [chadxz/imap-simple#16]
I am using this package to read XML email notifications from eBay. I have noticed sometimes the XML contains errors that are NOT found in the original emails.

An example:

`<?xml version=3D"1.0" encoding=3D"UTF-8"?>
 <soapenv:Envelope xmlns:soapenv=3D"http://schemas.xmlsoap.org/soap/envelope=/" xmlns:xsd=3D"http://www.w3.org/2001/XMLSchema" xmlns:xsi=3D"http://www.w= 3.org/2001/XMLSchema-instance">
 <soapenv:Header>
 <ebl:RequesterCredentials soapenv:mustUnderstand=3D"0" xmlns:ns=3D"urn:ebay:apis:eBLBaseComponents" xmlns:ebl=3D"urn:ebay:apis:eBLBaseComponents">
 <ebl:NotificationSignature xmlns:ebl=3D"urn:ebay:apis:eBLBaseComponents"=`

This continues through the entire XML file, every time there is an "=" it is replaced by "=3D".

I attempted just replacing "=3D", but there's some other errors, such as "<EIASToken>+seQ=3D=3D<=
 /EIASToken>" 

The end should look like </EIASToken>,  yet the equals are getting thrown in there as well. And of course, you can see the =3D's thrown everywhere.

Another example:

" <ConvertedCurrentPrice currencyID=3D"USD">109.75</ConvertedCurrentPric=
 e>"

Any ideas why this is happening? Again, in the original email files, the XML is showing correctly. Only in the data returned by this package are these errors found. And it's not every email - maybe 1-3 out of 50 emails.

**Comment by chadxz** [comment]
Never seen that in my limited use case. However, i find it an unlikely coincidence that the hex ascii code for "=" is `3D`. So that gives me the impression it's something to do with character encodings or conversions or something.

Would you be able to attach an example notification with any personal data redacted? I don't know that i'd be of much help without it.

**Comment by SpyridonZ** [comment]
Thanks for the quick response! 

Sure, will edit one without the personal info and then send it over.

**Comment by SpyridonZ** [comment]
I was looking in to finding some data to send to you, and made some progress figuring out the issue.

I noticed that all the files with "=3D" in it, were cut off as if they were using line wrap. Doing a little more investigating in to this, and it seems these problem notifications are using "quoted printable" encoding. 

So every time there's a new line, that generates an "=" character to signify the new line. But since the "=" character is already being used for something, all the actual "="'s in the rest of the file get replaced with "=3D".

**Comment by chadxz** [comment]
There's some special handling for quoted-printable encoded message parts in the library here: https://github.com/chadxz/imap-simple/blob/2060975a1df38db962eb3a97504c5c8088b574c7/lib/imapSimple.js#L218

perhaps something about that code is causing the issue you're experiencing?

**Comment by SpyridonZ** [comment]
I have to do a little more research. But, imap-simple may actually be processing the emails correctly, and it may just need to be decoded prior to XML parsing for it to work.

Is it correct that imap-simple is just intended on reading the emails and delivering them in the correct format they were sent? Should decoding out of quoted printable be a part of imap-simples functionality? Or should this be handled externally?

If it's only supposed to be reading, then I _think_ it's working properly and this is only a decoding issue. If it's supposed to decode as well, then there may be an issue.

**Comment by chadxz** [comment]
As far as scope of the library, I don't really have any specific thoughts on that. It would be great if your use case _just worked_, though. I imagine that if you feel the issue you're experiencing ought to be covered by the functionality of the library, it probably does? If we can figure out what the cause is, we can look and see if it makes sense to put a fix into the library for it.

**Comment by SpyridonZ** [comment]
For an update on this:

One of our employees made a dirty work-around for this issue using the utf8 package:

            var update = emailBody.hiddenData.replace(/=\r\n/g, "").replace(/\r\n/g, "");
            var decoded = utf8.decode(quotedPrintable.decode(update));

Hope it helps anyone having the problem!
