### ISSUE TITLE
The process is not exiting while it throws an connection error

### ISSUE THREAD

**Issue by gokulklenty** [chadxz/imap-simple#17]
The process is not exiting while it throws an connection error.

**Comment by gokulklenty** [comment]
The socket connection is not getting closed when it throws an error

**Comment by chadxz** [comment]
pull requests welcome

**Comment by gokulklenty** [comment]
Actually it was a problem with imap npm module you are using. It is fixed now, You have to change the version of imap to ^0.8.18.(Should be at least this version) I am making a pull request.

**Comment by chadxz** [comment]
As mentioned in #18, you don't actually need to change the value listed in package.json for the imap library to get the latest patch version, you just need to reinstall this package and the semver hat `^` will cause it to automatically pull the latest patch version.
