### ISSUE TITLE
Getting attachments with title, body and sender

### ISSUE THREAD

**Issue by gamelaster** [chadxz/imap-simple#20]
Hello!

Thank you for this library, really helpful!
But anyway, my skills with promises is still low, so I want to ask.
How to get attachments with title, body and sender???
I wanted to do it myself, but I have problems with "merging all information as final value via promises".

Thanks

**Comment by chadxz** [comment]
Do you have any code you can share? Maybe of what you have tried so far?

I'd be happy to help solve your problem.

**Comment by gamelaster** [comment]
I just depends on your example script of fetching attachments, I didn't any other changes to code!

Really thanks for this, maximum helpful for me :blush:

**Comment by chadxz** [comment]
Have you tried to solve it on your own already?

**Comment by gamelaster** [comment]
Yeah, but my promises skills is low and I doesn't how to on final return the attachments and everything in one array. Sorry for disturbing for banally issue but really I can't help for myself 😊

**Comment by chadxz** [comment]
To combine the results of two promises into a single result, you'd use something like

```
Promise.all([
  promise1, 
  promise2
]).then(function (results) {
  promise1Result = results[0];
  promise2Result = results[1];

  // do stuff with results
});
```

Alternatively, you could use a tool like [Bluebird](http://bluebirdjs.com/docs/features.html) to get access to some helper functions for doing things like spreading the results into separate params in your callback instead of a single array param.

**Comment by chadxz** [comment]
LMK if there's anything else I can help with.

**Comment by melitus** [comment]
@chadxz I have a problem when I saved downloaded attachments to a directory using 
```
      const writable = fs.createWriteStream('public/resumes/' +  attachment.filename); 
```
When i open the donwloaded attachment, I got the pics below.
![Screenshot from 2020-02-02 10-01-22](https://user-images.githubusercontent.com/5014464/73605862-0049a180-45a4-11ea-9482-e080dba19f06.png)
