### ISSUE TITLE
3D character in body

### ISSUE THREAD

**Issue by casalot** [chadxz/imap-simple#23]
Hi,

I have used your sample code to get emails from an inbox. But, the `body` has `3D` characters all over the markup, hence the mail not rendering properly.

e.g: *`<meta http-equiv=3D"Content-Type" content=3D"text/html; charset=3DUTF-8">`*

I have already tried `.toString('utf8')`, but makes no difference.

Any ideas?

**Comment by chadxz** [comment]
This seems related to #16. I have not dug into the issue to determine the cause.

**Comment by casalot** [comment]
FYI: I have just tested this with the `node-imap` package directly, and I get the same issue.
