### ISSUE TITLE
Timeout Issue

### ISSUE THREAD

**Issue by casalot** [chadxz/imap-simple#24]
I have the following config:
```
let imaps = require('imap-simple');
var imapConfig = {
    imap: {
        user: '****',
        password: '****',
        host: '****',
        port: 993,
        tls: true,
        tlsOptions: {
            rejectUnauthorized: false
        },
        authTimeout: 30000,
        debug: console.log
    }
};
```
And, here's the implementation
```
  imaps.connect(imapConfig).then(function (connection) {
    console.log('CONNECTED:',connection);
    return connection.openBox('INBOX').then(function () {
      console.log(''In the INBOX);
   })
})
```

Now, when running this, I immediately get the following: `[connection] Connected to host`, and then after 30 seconds this: `[connection] Closed`.

I don't seem to get any of the other `console.log`s. Is this a connectivity/authentication issue? Or am I missing something in my logic?

**Comment by Akamaozu** [comment]
When you connect to the inbox, your console.log seems to be broken.

console.log(''In the INBOX);

Additionally, I've noticed `imap-simple` swallows errors, which is likely why you don't see the script crash.

**Comment by casalot** [comment]
Thanks, @Akamaozu. I have fixed the `console.log`, but still getting the same issue.

**Comment by Akamaozu** [comment]
@casalot Your promise should look something like this:

```js
imaps.connect(imapConfig).then(function (connection) {
    console.log('CONNECTED:',connection);
    return connection.openBox('INBOX');
}).then(function () {
    console.log('In the INBOX');
});
```

**Comment by casalot** [comment]
I have tried your suggestion, as well the examples in the `README`, but still having the same issue ...

**Comment by Akamaozu** [comment]
@casalot sorry i didn't think of this immediately.

Add a catch block and `console.log` the error; it'll help you see exactly where the it is failing.

```js
imaps.connect(imapConfig).then(function (connection) {
    console.log('CONNECTED:',connection);
    return connection.openBox('INBOX');
}).then(function () {
    console.log('In the INBOX');
}).catch( function( e ){
    console.log( e );
});
```

**Comment by casalot** [comment]
@Akamaozu, timeout error:

```
{ [ConnectionTimeoutError: connection timed out. timeout = 30000 ms]
  message: 'connection timed out. timeout = 30000 ms',
  name: 'ConnectionTimeoutError' }
```
I've tried increasing the timeout, but no luck.

When testing the connection on the command line, using `openssl`, it connects fine. So, the API server does have access to the IMAp server.

**Comment by chadxz** [comment]
> I've noticed `imap-simple` swallows errors

@Akamaozu more so than promises generally do? That would be something I would want to fix if so.

@casalot you might want to try your simple use case with the regular [`node-imap`](https://github.com/mscdex/node-imap) library to see if the problem exists there, too. That would indicate a more general problem and not something specific to this library (which wraps around [`node-imap`](https://github.com/mscdex/node-imap))

**Comment by casalot** [comment]
@chadxz, I'm starting to wonder if that doesn't come directly from node TLS. When I search the `node-imap` and `imap-simple` code for that particular error message, I can't find anything.

If I specify `rejectUnauthorized `, I don't have to worry about any cert settings, is that correct? Just trying to eliminate all possibilities here.

**Comment by chadxz** [comment]
It is my understanding that if you set `rejectUnauthorized: false` then it should allow even invalid certs.

**Comment by chadxz** [comment]
LMK if there's anything else I can do to help.
