### ISSUE TITLE
possibility to add a sort criteria in search / fetch options

### ISSUE THREAD

**Issue by dohomi** [chadxz/imap-simple#26]
Hello,
is there a possibility to search an `INBOX` and get the newest results first? I found the `RFC5256` inside of `node-imap` and this looks promising. But I have no idea if this is possible with imap-simple. Could you give some advise? Thanks!

**Comment by chadxz** [comment]
could you link to what you're talking about RE: RFC5256 in node-imap?

**Comment by chadxz** [comment]
nevermind i found it: https://github.com/mscdex/node-imap#extensions-supported

**Comment by chadxz** [comment]
The `sort` method is not currently exposed in imap-simple. If you wanted to try to add it to the library, it would be implemented as a member of the ImapSimple prototype. It would process the results of the node-imap sort() call using the same handler passed as the callback to `self.imap.search()` in the ImapSimple.prototype.search method. I am not actively developing on this library, but if you want to submit a PR i'd be happy to review and provide feedback and answer any questions you may have to the best of my ability.

**Comment by dohomi** [comment]
Hi @chadxz ok thanks. I will see if I am able to get this pieces together.
