### ISSUE TITLE
how to limit the amount of messages

### ISSUE THREAD

**Issue by timaschew** [chadxz/imap-simple#33]
First of all thank you for this great library!

I wonder if and how it's possible to limit the amount of messages.
I've only seen to limit the messages for a specific time time, but I would like to show build some queries which provides the common pattern of offset and limit
For instance: 
- show last 10 message (offset: 0, limit: 10)
- show previous 10 messages (offset: 10, limit: 10)

**Comment by chadxz** [comment]
In this library, you can pass `searchOptions` and `fetchOptions` to the `search()` method. These options objects are passed along to the underlying node-imap library's search and fetch methods, respectively. The `search()` method in this library combines these two underlying node-imap methods.

The author of node-imap has discussed how to implement a sort of limiting result set [here](https://github.com/mscdex/node-imap/issues/221), but it relies on being able to do the search and fetch as separate operations, only fetching a subset of the entire search result set.

Here are some things you could try:

- fetch the entire list, then paginate through the results in your app.
- make a change to this library to allow passing in a `limit` and `offset` to use for only fetching a portion of the whole search results.

**Comment by chadxz** [comment]
lmk if you need anything else.
