### ISSUE TITLE
Text body is not getting right charset (wrong accents and other special characters)

### ISSUE THREAD

**Issue by bgbraga** [chadxz/imap-simple#34]
The imap-simple API have two methods with different behavior.
For get subject (using code below) I could get fine special characters like accents á ê ç ã.... etc.
```
res.parts.filter(function (part) {
                    return part.which === 'HEADER';
})[0].body.subject[0]
```

BUT the text body (using code below) is showing =C3=AA instead of ê (for example).

```
res.parts.filter(function (part) {
                    return part.which === 'TEXT';
})[0].body
```

I tested that function from pull 25. It fixed the problem, but it is too generic.
https://github.com/chadxz/imap-simple/pull/25

```
function convertMessage(message) {
     return new Buffer(message.replace(/=([A-Fa-f0-9]{2})/g, function (m, byte) {
         return String.fromCharCode(parseInt(byte, 16));
     }), 'binary').toString('utf8');
}
```

**Comment by chadxz** [comment]
How would you suggest fixing the pull request? Would you mind commenting on
that thread to add to their investigation?

**Comment by bgbraga** [comment]
I think the better idea is check what is already doing by header to fix the problem and do the same with text body.

I think it is related with Imap.parseHeader. 

Code:
https://github.com/mscdex/node-imap/blob/941b071f80f20e6b799ecfff065fcbeed1670672/lib/Parser.js

Looking at the code I see an interesting thing:

They are using a regex: `RE_QENC = /(?:=([a-fA-F0-9]{2}))|_/g,` that is the same of PR 25.

So maybe that regex is the right way to fix that.

**Comment by mk-pmb** [comment]
This is definitely about quoted-printable encoding. Please compose a test email to yourself with the exotic characters in the subject and possibly other headers, too. Save it as draft, view the message source of that draft, make a gist of the full mail source and show us.
To test whether there's magic in your mail server, send the mail, receive it with `imap-simple`, compare the source of the received version, and if anything changed, make a gist of that as well.

I suggest let's have the library try its best to offer decoded bodies and headers by default, and offering something like `rawHeader` and `rawBody` for people who need them (e.g. for quirk detection). For cases where decoding is a waste of CPU cycles, let's make a config option `rawOnly` that makes `imap-simple` skip any attempt at encoding guessing and put `false` as the message text and headers dictionary.
