### ISSUE TITLE
Error: read ECONNRESET

### ISSUE THREAD

**Issue by SpyridonZ** [chadxz/imap-simple#35]
We have been getting an error that seems to be from the package (our console logs have consistently had this error when the imap-simple package was checking email).

    2017-05-04 13:03:39-07:00 events.js:72
    2017-05-04 13:03:39-07:00  throw er; // Unhandled 'error' event
    2017-05-04 13:03:39-07:00  ^
    2017-05-04 13:03:39-07:00 Error: read ECONNRESET
    2017-05-04 13:03:39-07:00 at errnoException (net.js:905:11)
    2017-05-04 13:03:39-07:00 at TCP.onread (net.js:559:19)

I'm not sure exactly what part of the call is causing this, it's a fairly standard call:

    var config = {
        imap: {
            user: 'XXX',
            password: 'XXX',
            host: 'imap.gmail.com',
            port: 993,
            tls: true,
            authTimeout: 3000
        }
    };

code:

    imaps.connect(config).then(function (connection) {
            connection.openBox('INBOX').then(function () {

                var searchCriteria = [
                    'UNSEEN'
                ];

                var fetchOptions = {
                    bodies: ['HEADER', 'TEXT'],
                    markSeen: true
                };

                connection.search(searchCriteria, fetchOptions).then(function (results) {

After that is just parsing, but it seems the error is happening in the connection call according to the error.

We basically have it continually checking email every couple minutes. Typically we get the error 1-2 times a day. Sometimes we do not get the error for a few days. Some days we have had 10+ times a day. It's a pretty major issue on those bad days, so I would like to get this resolved. 

Any advice on how to track this down and/or fix it?

**Comment by chadxz** [comment]
http://stackoverflow.com/a/17637900/355743
