### ISSUE TITLE
outlook support

### ISSUE THREAD

**Issue by rhsu0268** [chadxz/imap-simple#36]
Does this module support outlook as one of the host or is it only for gmail at this time?

Thanks,
Richard

**Comment by chadxz** [comment]
I've only ever used it against Gmail, so I don't know. If you end up making modifications to get it to work against outlook, contributions are welcome :)

**Comment by vuchl** [comment]
@rhsu0268  If your Exchange is running the IMAP service and the IMAP ports are open you can connect top IMAPv4.
