### ISSUE TITLE
gmail access token

### ISSUE THREAD

**Issue by spyeadon** [chadxz/imap-simple#37]
If I want to retrieve all gmail messages for a given google account, do I need to pass an oAuth token to validate my gmail imap connection? Isn't that the only way to gain access to those messages? How do I do that with this API? And then when I have access, how do I retrieve _all_ the message for a given user?

**Comment by chadxz** [comment]
> do I need to pass an oAuth token to validate my gmail imap connection? Isn't that the only way to gain access to those messages? 

I don't think so. I believe all you have to do is enable "[less secure apps access](https://myaccount.google.com/lesssecureapps)" to your gmail account, then access it like any other imap account.

> how do I retrieve all the message for a given user?

Make sure your search criteria doesn't limit the results, then iterate through the search results. If you have an enormous amount of messages that match the search criteria, you may encounter memory issues. If you run into that, you may be better off using the base [node-imap](https://github.com/mscdex/node-imap).

**Comment by spyeadon** [comment]
Thanks!

**Comment by melitus** [comment]
@chadxz, I have tried enabling "less secure app access" but I could not connect to the Gmail on live server but connected perfectly on localhost. What could be the problem?. Thanks
