### ISSUE TITLE
Bad config does not throw error

### ISSUE THREAD

**Issue by jmbeach** [chadxz/imap-simple#38]
I initially configured my options for connection like so:

```
var options = {
  user: 'my user',
  password: 'my pass',
  ...
}
```

But the library requires:

```
var options = {
  imap: {
    user: 'my user',
    password: 'my pass',
    ...
  }
}
```
The connect function just never received the callback and no error was thrown.

**Comment by jmbeach** [comment]
Also, I needed `tls: true` to get a successful connection and received no errors before that either

**Comment by chadxz** [comment]
Willing to accept a pr to fix

**Comment by krishan1kamal** [comment]
You can check connection by passing callback in imaps connect you get error if any error accrued during connection 
 var imaps = require('imap-simple');

var config = {
    imap: {
        user: 'your email',
        password: 'your password',
        host: 'hostname',
        port: 993,
        tls: true,
        authTimeout: 3000
    }
}; 
     imaps.connect(config,function (err, connection) {
         if(err) {
          res.jsonp({'status':'error', 'messageId':204, 'message':'Please check your connection string.'}); 
         } else {
            res.jsonp({'status':'success', 'messageId':200, 'message':'email  connection success'}); 
         }
         
     });
