### ISSUE TITLE
[Feature Request] Amend subject

### ISSUE THREAD

**Issue by mk-pmb** [chadxz/imap-simple#39]
Hi, thanks for imap-simple, looks very promising!
I'd love if someone could add a feature to amend the subject of a message. I'd mostly use to to add markers in front or at the end.
What's the most safe way to do it? Do we have to save an amended copy of the message and then, if the server claims it was saved entirely and successfully, delete the original one? Sounds like lots of data transfer if it's a long message.

**Comment by 8perezm** [comment]
I would like to know the same
