### ISSUE TITLE
get complete email as a string or a stream

### ISSUE THREAD

**Issue by dpatte** [chadxz/imap-simple#40]
Maybe I am missing something, but I need to download complete messages. I can access parts to decide what to download, but how would I get the complete messages once I have decided which messages I want to download?

**Comment by chadxz** [comment]
It's not your fault. The original [node-imap](https://github.com/mscdex/node-imap) library is complicated to understand and this library is only a thin layer of abstraction over top of that. As a result, you still end up having to understand node-imap to use this library.

To answer your question, if you follow the first example given in the README, the body of the message would be in, for example, `results[0].parts[0].body` when the `part.which === 'TEXT'`. You can print the results of a call to `search()` to get a better understanding of the data structure. As long as you don't explicitly suppress message bodies in the fetch options, the message will be there.

I hope that is clear. Post back if you are still having trouble and i'll try to help when I have some time.

**Comment by dpatte** [comment]
Hi chadxz. Actually I am looking for a way to get the full raw email message, all of it, not just parts of it, so I can stream it to a file.

**Comment by chadxz** [comment]
No idea. Check out the underlying library. If it supports that, and you wanna see it supported in this library, I'm willing to accept pull requests

**Comment by dpatte** [comment]
Thanks for your help. So how would I go about programmatically accessing the imap object that imap-simple wraps? It looks like imap support a part called "" (yes - empty string) which provides a stream of the whole message.

**Comment by chadxz** [comment]
From the first example on the readme:

```
imaps.connect(config).then(function (connection) {
  // ...
});
```
the `connection` object is an instance of `ImapSimple`, which exposes a `imap` property that is the node-imap instance

**Comment by chadxz** [comment]
Keep in mind though that this is circumventing the normal api and semantics of this library if you interact with that library directly. No telling how much luck you'll have doing that.

**Comment by dpatte** [comment]
Got it working great. Thank you. I simply added '' to the bodies attribute, and the full raw msg was available. Thx.

**Comment by chadxz** [comment]
👏
