### ISSUE TITLE
How to fix ReferenceError: Promise is not defined

### ISSUE THREAD

**Issue by LaKanDoR** [chadxz/imap-simple#44]
1|app      |     at Object.<anonymous> (/usr/local/lib/node_modules/pm2/lib/ProcessContainerFork.js:70:21)
1|app      |     at Module._compile (module.js:456:26)
1|app      |     at Object.Module._extensions..js (module.js:474:10)
1|app      |     at Module.load (module.js:356:32)
1|app      | ReferenceError: Promise is not defined
1|app      |     at Object.connect (/var/www/vhosts/chattet.de/maiwell-mail.chattet.de/node_modules/imap-simple/lib/imapSimple.js:439:16)
1|app      |     at Object.<anonymous> (/var/www/vhosts/chattet.de/maiwell-mail.chattet.de/app.js:14:7)
1|app      |     at Module._compile (module.js:456:26)
1|app      |     at Object.Module._extensions..js (module.js:474:10)
1|app      |     at Module.load (module.js:356:32)
1|app      |     at Function.Module._load (module.js:312:12)
1|app      |     at Object.<anonymous> (/usr/local/lib/node_modules/pm2/lib/ProcessContainerFork.js:70:21)
1|app      |     at Module._compile (module.js:456:26)
1|app      |     at Object.Module._extensions..js (module.js:474:10)
1|app      |     at Module.load (module.js:356:32)

**Comment by chadxz** [comment]
Use a Node version that supports native Promises, i.e. Node 4+

Or pin this library in your `package.json` to v3.1.0, which was the last version that supported versions of Node without native Promise support.
