### ISSUE TITLE
How to fix ReferenceError: describe is not defined - test/index.spec.js

### ISSUE THREAD

**Issue by LaKanDoR** [chadxz/imap-simple#45]
mike262:/var/www/vhosts/chattet.de/maiwell-mail.chattet.de/node_modules/imap-simple/test# pm2 log index.spec
[TAILING] Tailing last 15 lines for [index.spec] process (change the value with --lines option)
/root/.pm2/logs/index.spec-out-4.log last 15 lines:
/root/.pm2/logs/index.spec-error-4.log last 15 lines:
4|index.sp |     at Module._compile (module.js:456:26)
4|index.sp |     at Object.Module._extensions..js (module.js:474:10)
4|index.sp |     at Module.load (module.js:356:32)
4|index.sp |     at Function.Module._load (module.js:312:12)
4|index.sp | ReferenceError: describe is not defined
4|index.sp |     at Object.<anonymous> (/var/www/vhosts/chattet.de/maiwell-mail.chattet.de/node_modules/imap-simple/test/index.spec.js:3:1)
4|index.sp |     at Module._compile (module.js:456:26)
4|index.sp |     at Object.Module._extensions..js (module.js:474:10)
4|index.sp |     at Module.load (module.js:356:32)
4|index.sp |     at Function.Module._load (module.js:312:12)
4|index.sp |     at Object.<anonymous> (/usr/local/lib/node_modules/pm2/lib/ProcessContainerFork.js:70:21)
4|index.sp |     at Module._compile (module.js:456:26)
4|index.sp |     at Object.Module._extensions..js (module.js:474:10)
4|index.sp |     at Module.load (module.js:356:32)
4|index.sp |     at Function.Module._load (module.js:312:12)

**Comment by chadxz** [comment]
the tests are meant to be run with mocha. mocha is responsible for supplying the describe function. See the `test` script in the module's package.json
