### ISSUE TITLE
How to fetch email as HTML body ?

### ISSUE THREAD

**Issue by wiflux** [chadxz/imap-simple#54]
Currently I am getting email body including headers and inline attachment. How to get or parse this into html format ?

Example email :-
`--00000000000027fdc7057d257064\r\nContent-Type: multipart/alternative; boundary="00000000000027fdc4057d257063"\r\n\r\n--00000000000027fdc4057d257063\r\nContent-Type: text/plain; charset="UTF-8"\r\n\r\nI am fine.\r\n\r\n\r\n[image: kakatua.jpeg]\r\n\r\nOn Sun, Dec 16, 2018 at 9:05 PM <dharminder@dp360crm.com> wrote:\r\n\r\n> Hi,\r\n> How are you ?\r\n> *Dharminder Team*\r\n> *DP360 CRM*\r\n>\r\n\r\n\r\n-- \r\nDharmender Singh Negi\r\nPHP Developer\r\n\r\n--00000000000027fdc4057d257063\r\nContent-Type: text/html; charset="UTF-8"\r\nContent-Transfer-Encoding: quoted-printable\r\n\r\n<div dir=3D"ltr"><div><br></div>I am fine.=C2=A0<div><br></div><div><br><di=\r\nv><div><img src=3D"cid:ii_jpr1ztly0" alt=3D"kakatua.jpeg" width=3D"276" hei=\r\nght=3D"183"><br></div></div></div></div><br><div class=3D"gmail_quote"><div=\r\n dir=3D"ltr">On Sun, Dec 16, 2018 at 9:05 PM &lt;<a href=3D"mailto:dharmind=\r\ner@dp360crm.com">dharminder@dp360crm.com</a>&gt; wrote:<br></div><blockquot=\r\ne class=3D"gmail_quote" style=3D"margin:0px 0px 0px 0.8ex;border-left:1px s=\r\nolid rgb(204,204,204);padding-left:1ex"><p>Hi,<br>\r\nHow are you ?</p>\r\n<div style=3D"letter-spacing:0px"><em><span style=3D"line-height:5px"><stro=\r\nng>D<span style=3D"line-height:10px">harminder Team</span></strong></span><=\r\n/em></div>\r\n\r\n<div style=3D"letter-spacing:0px"><em><span style=3D"line-height:10px"><str=\r\nong>DP360 CRM</strong></span></em></div>\r\n\r\n\r\n\r\n\r\n\r\n</blockquote></div><br clear=3D"all"><div><br></div>-- <br><div dir=3D"ltr"=\r\n class=3D"gmail_signature">Dharmender Singh Negi<br>PHP Developer<br></div>\r\n\r\n--00000000000027fdc4057d257063--\r\n--00000000000027fdc7057d257064\r\nContent-Type: image/jpeg; name="kakatua.jpeg"\r\nContent-Disposition: inline; filename="kakatua.jpeg"\r\nContent-Transfer-Encoding: base64\r\nContent-ID: <ii_jpr1ztly0>\r\nX-Attachment-Id: ii_jpr1ztly0\r\n\r\n/9j/4AAQSkZJRgABAQAAAQABAAD/2wCEAAkGBxMSEhUSEhMVFhUXFxUVFRUXFxUVFxUVFRUWFxUV\r\nFRUYHSggGBolHRUVITEhJSkrLi4uFx8zODMtNygtLisBCgoKDg0OGxAQGy0lHyUtLS0tLS0tLTAt\r\nLS0tLS0tLS0tLS0tLS8tLS0tLS0tLS0tLy0tLS0tLS0tLS0tLS0tLf/AABEIALcBFAMBIgACEQED\r\nEQH/xAAcAAABBQEBAQAAAAAAAAAAAAAFAAIDBAYBBwj/xABAEAABBAEBBAcDCQYGAwAAAAABAAID\r\nEQQhBRIxQQYiUWFxgZEHE6EUMkJSkrHB0fAjYnKC4fEVJDNzorJTk9L/xAAaAQACAwEBAAAAAAAA\r\nAAAAAAACAwABBAUG/8QALhEAAgIBAwIFAgYDAQAAAAAAAAECAxEEITESQQUTIlFxMpFCUmGBobEU\r\nNOEj/9oADAMBAAIRAxEAPwCPbEnFVdnE2u7RktO2e1CuRsvpDUDk2d67E1RTcVpTMzW5A964CuSB\r\nSxM7ULKaHMatLsSHRAXSMjAL3NaNNSaGvej+HtKGPqvka00CASBYJoUeHFLt4wRB+JincNELxtu4\r\n7iAJW6gkcrDfneY5jlp2ooJGuFtII7j5FJhHLDIHaJhyKUkoQqeTVVdXkGQQfNaqPfqq/v1GJLKw\r\nRrfUKwSyyIblIiQqGYNFuikkaIAGY6phnoJmU+ih0sy0VMCaL/ylSsktCGSK/jOTGxTReY1TMbSi\r\njKmDUqUQGg5s5ttCJNiVLZTaCKtCijsOjHYoZrdEHyNSj+cNEClbqhlsMSO4saKw6IdAUQjdouFq\r\nI9TyZZrckkch2Q8hTTSUqOTKl1adqS9hLjuRyG0yB9OUQemxO6y9Bp6elGiEDQRv0VfJk0UYl0VW\r\neVa5PCNKQOmNkpJsnFJJLM1nSaonspuizzZt5wWr2VFoEEN2HJ7BFjNEPy5mssucB4mr8O1M6Q9I\r\nI8Vu6bLyNKAoeJJpeY7R27LKTvSOIPInSvDkmOWBajnc1m0OlbWEhrQTyNn4ikIyulz3DhuntaTX\r\njRtZMuTXPVdTLwgjPteR1guNHly9FTdlu01OnDU6Ks4phKHJAm3a8oIO+bDg675jn8UZ2R01yYC3\r\nckJA3raTYO8b+BAPisvDC556otXP8JmaGuLT1jTRzJoGvHUKdW5R9D9EOlcedCNQJQ23s9NR3ahT\r\n5btVhvZv0Skid8qfI4W3dDG6WLaTvbw4dWvNehmBh4sv+Z34EJF+prg+l8gtpgt0tJRS2UYZixHj\r\nG31efxViPDg/8bb81k/y685wylDPcGNVbMZYWj+Sw/Vrzd+aik2bC4cSPA/mCmLWVvsxySXc802j\r\noSg0xXpOf0ND9WTEfxNDviCFn83oVkN+buP8HUfRwA+KdDWU/mx87EdbfBmI0Qx3KPJ2XNF/qRPb\r\n3lpr7Q0+KbDa1Kae6YlxC8DldjKH4wV+MotmUoh7Z/AIsAgWNkABX48tXgPBYyWoRkRaojNkAqlK\r\n8JcolopMdqrUctKi94tP98Fz3R6mKcNyTLehrnklWnzBVZHhaIUpItVHKT2aG1EZQoZsjRak8Ico\r\nYLz8lU58sIZLllUZMizohlMJIJSZQtcUUOKSLSQZJlGT2c/ri1os3pCzGjI0LyOqL594u1ksiXc1\r\nHFAcmcuJJUg8IXBN8ku1NovmeXvNn4DwHIKm4rgXCOQ4ogmxWnQ475HBkbHPceDWAucfAAWVuOhn\r\ns4flASzksj7B8535BeqbH2Bi4Lf2MYaaov4uI7LK5eq8UqqfTH1P+PuNVT6eqWyPL9i+yfLkaHZD\r\n2QA/RP7STzDTut9Se4I6z2Nw0Ly5CedRsA8tTS1W1elWPC7cklp1fNa10hb/ABBp0Umz+kEM+kMz\r\nJDzZe5IP5HfmsMr9ZJdTfSvjb7mWc5LiOwO2V7OcSA2z3m9Xzi+78qpBulm7DIIWXbATwA+cG7pB\r\n+38FvYcsO/VeoWO6USj5ZRqzHCz1fIT8C30TvCXOWrXmNvZspT6kano+SMWEEfQafVXC8qdkjAPA\r\nUPuSYGnv+CbfFWTbzyZPVl4KhkcuslKvtxWlL/DhyKS9K+zCxYt8FL3x7U4TEKwcIqF2OUqWjsQH\r\nWzoyT2qZuSVAIinhipaea5KU37lhmSVSydl48urowD9ZvVPw4+astClESZHTzW8Hj42HLUWrvn5M\r\n/kdGK1hff7r+P2hx9AhGTBJH89rm+I0PgeBW6bEeRXXNsEOAIPEHW/zWqGpvg/Wsr7Do6iL+pYMF\r\nBI5WRkkLRz7EjOrBunsHD05eSoS7KLeI8+S6NephPbh+zGxlGXAMZkOKbLlEK+7CoqvPipjbDwgT\r\nLlFQvz6XcuKiqLmWgxkvCLYzLXHTKGKFXGQCkaTJkibMmPsqwMdWIoAr6RbkCn41qKPE6y0nuAqU\r\n8NG0LRcWWcWIboSVNmTWi6hC6TyPPyi46+VIcTzXZHlR2iRbOklbn2d9DnTvE0oqNpsA8Xn8lJ0F\r\n6EuyCJpmkMGrW8N7949y9l2ds9sTQ1ooLj+Ja/pi66+e7JGO+53Hi3BQGgFUqOZLdg8OJ8OaKvah\r\n+VBY04rzkHhpsK+xuPSjwzbu03RzSOLGOd7yTe32kjeJLS4ixZFc74DRDf8AFHyAPIDCwHdcxoZu\r\nkFzgQWi7u+N6acNF6V0m6Lx5Dt4O3HnQ3qHVoCQSNeGoJviRdk09h9CWRva6V4dRsNIDWDhqW2XP\r\nPYNBpqvWR19Xl5bM3mRwbXZoJYx7/nbrS/h87dF8NPvWKnyzNtXTgJWN8o2NLv8Ak161m1totiic\r\n+9Gi/E/qvVYf2fQOkypJXfQBLjyL5Sbr0f6rDofTGy99o4XywE9mz1SF6vRkITA7VWHTrI9W+Ea9\r\nBpVP1MJCRPaewoY2dPGUrjqF3Ov/AI+OAoJD2rpchzMhPbkLTXqmuGZrdFCfKLZrsS3QoGzp4ctU\r\ndYn9RyrvDpQ3iPLU5qi3lI2RPjKMt0YWnHZkgKco7C6o+Ch4Ti20wLm+qeGsNFbp5RDkYYPDRDMm\r\nGuIRwPXJGBwoiwiha4/qv5NUNR2n9zBZkeqptxtVo9s7Icy3s6zOfa3xHZ3oXALWqucZbo187oib\r\njJSCldcFXnbonZKaKW/qrENqOOCyrrY6CpyFMe3gqmZwVy1TyUvOS4gaU6pKSVuqSDIzJ4493JaL\r\noJsf5TkNbybRPrxvlz/os4V6h7F8H/Wm/hYO3mSe7ig1U+ipst7s9TwccMAa0Cgrbyoo9FKSvJzY\r\n5RGOKieFM5QuKRJewuUShlYrXcR9yo/IImanVE5G2quXHY+dXeKseqOEZCHAwftK2iGRxxNrr241\r\n9UUGgnxJPkr/ALPdnvZhtkNl0rjJfE7p0ZfkAfNYbprkx/KZI3GaQxfs29dgGgFjRn1i4L1HYzwy\r\nCNgEjN1jRQka4Aho0BczUeK9I4U16WMLW0nvty/4+BduFHGQjAw2nSOVSPIPOSQ/+v8A+EyV7jqH\r\n/aaD8QQuVqI6XbyW/wBzT4fqoU5U5f2Ww9ISKkHv/cPgXD8E/wB6RxafKj9xv4LOoPsdyGv00vxo\r\nuskUkcuqoslaOdfxAt/7UpowTrxHaNR6hE65R7DlZVP6WmXxLWqlZLY0QySQhSMmpRTaKcEwqJF0\r\nupDmZKkdkhPqucWc/U6KNm4QD09sqqMksWuxvsLfC/qOBdprKnvwXRKFwvVOSSgkyVPT23Mrky6x\r\nyma5UGSqWSWghz6thsIuexZEiC7S2c296OgeJZyPeOxdlzCCqsmUSnwpnnKOvptJKP1PYrFM92pS\r\n4O50e3tXdw0tiewVtLg9+CKKPVPlCTdFHlS0EtsxyI3lU3mypXy2o1aLgU5W6pJ8x1SUwGeH+K+g\r\nvZ1sr3GFGS2jJ+1rsa8Asvvqj5r5/hiL3NYBZc4NA7S40B8V9O4mQD1Qb3aaa4AgcAf1WixeJP8A\r\n80goclzdTk0/r+y6AvOyRpR0prgnLiFRyRoheEF2/nNgikmd9BpdXaWiw3zIA80akKx/T/GdLiyR\r\ns1Jr4ODhx72ha9PCPWk+BE4ZPJOjuKcnMja/rbzzJIe0A7zifE/evZXvXj2ws1+BOJJoX1RaRWtH\r\njuk6E6dq9K2V0ixsnSKQb1XuO6r/ALJ4+Vrf4nXZZJOKzHHYw6iDe/YI76RcnTt3hpxCj+9ciUXF\r\n7mQ6JE8TKIpEKJZAci03JPaoo63i4gXy/uoKKbZWiuyUeGTra4YUZld58Cd4ejrXMbJ33OHUAHZY\r\n/Ej4IbZXYSQtcLYy2simOq199SfTJ/uFpSGVZq/P7tfgmAk6g33jWvRCsglzmolFO2g0tFfrmmrS\r\n02bwePk6NfjkoxXmrPwWmZFBT4mToq75GEE1qBf6KqR5rHEAGieR/P8ANIt0dtXKOjVqtPq44TCe\r\nVNqArrGaBA3B1/d4ItBltrwCKN3TFRmYNV4f04ceCbmAppjQQoZYJcbAPiqh2ryJWqFWXt2Kp0fV\r\nvEnynWqL5VBNl3wVd03YuvXwdbGEWhkhEcTI3+qePLvWeEnapWvqiD6cimOCaBbUl0sNytoofmFE\r\nm5TZg08H8HdhI5+KifhWVlcHk5Vtbi8MHRsTnDVFW44Cgnx0fSSKwCZI7KSmfxSVYCweGY2S6J4k\r\nZo5urTx3TRAI7xdjvAXvHs2oYkcZdvPDeubvrOG+RfcHgeR714IQtr7NOkzsfJZE+3MmkZGOHVdI\r\n8NLr7LIJSNVV5lbJwz3VjOaeQlG+xacQvLT5NcSMpr09cpCmE0VZEK2hDvCkZkYqj4+KNSaYODJZ\r\nWzQbBGnes9ndFYT1gzdPJzCWkHtFaWt9kxIfNCtUNRJcMHoMeyHNi/05xI36sw1+23X1ViPbEjNJ\r\nonMvmOu37TeA8QFoJYQ0bxQDLy9e/gP18V0as3x9aT/XuYrqK88ErdoB1Oab7CDYU7Nod6zrIhd1\r\nr28CfEhWnxODbsoZ6D8pjlp0Hhmhd+VLMtmfyUjctw4tPlr9yzPSSXYW6H2NKcj+qkbkClnBtIHj\r\noVPFn8+Xih8l9xUq2aFkgKktBY8kcVahyfRC65IVgtTvceo3S+J7lPgQNjNjU9qqNmUwlW7TamUc\r\nKSygJSkliLwXMzaHuiC06niCA5tfwnRLfJaHciOKFwQhx3n2ddAr0+aGNPwC2W6SNsc17fp2/wCH\r\nU0ni8qmoT9XuMxXam6IQTaWSWu7kQhDpBY07+3wQrakR+lxHYsVXVXZh/Y9VpnTZFyrZyLPvmphl\r\n96z89t1XIcyzxXVhYmSytxNI2YFOZPXPRA2ZXerDMi1oUjO4hzHzCNQSe38wtTgZIkYHc+B8f66H\r\nzXnzZ0f6L59P3HcHaef0fxHmhlJZAtp6621yjWbirZPBXC7TghuW9RnMQKl4pLpSSizwshNBIqtK\r\nNgjQgjhXwXSFwFQY4nv/ALP+kwyoGbx/aBoa8fvMAaT5/O81r180dGttvw5mysstHz2fWbz8+wr6\r\nE2VtVs7Q5psEA+v9q9VwdfpeiXVHhhQljZl9IJw1KQC5qQ7JESonDQ+SsObqFG8ff+CLBAdMxD5Y\r\n7KMSxoVtJ24x7+xpI8eXxVQi3JR9y29sgTa8/Fg5cfRZTP4o6+TeBJ4nVA9oFeprqVcFFHNk+p5O\r\n4zgVesFtKjs9lq9I2kzIqTKLmKt70tKKMhtRZmFY0SJLJSzycaQ8cj8Ux2A3sI/hNf0UOA8h1FGm\r\nMsJaRJSBwwXfRk+0PxH5KXdlZxZY7W074DX4KeSIhMhyTdLPZCWcCHHL4GxZwvjr2c/RXY8pTDHa\r\n/RwB8RaR2Mz6LnM/5D0P5o5USSygZaaI6ObUJ01Oc3sCqvwZmcAJB2t4/ZOvpabHli6OhHEHQjxB\r\nR02OO0jPPTzi+pBhsgQbMmMriAPCuzvVluRofAp+E0NF8zxR2zjY/V2+4zR3WaZuUeQBm4hGjh5I\r\nFJHuOK1W2Wk270WaneDoeKXTZ2Z7bTXLU1KffuiJk57VOzJVL3RH6/WicLW6M2A4haHItEcLL3SO\r\n2wQeyuCzsb0XwnDmhslsOpW56vBP7xjXj6QB9eKG57qUXRnKuAt4lrq8iAfvtRZb7cmKeYpnEur8\r\nuyUfZlZdUrGpKC8HgtppK7SYrwX1Dg5bHoF0r+SPa2Vx911qPHcvUjwvXu17VjU4IJwU10so+otn\r\n5bXNBBu/uugrQPNeNezrpS5o9zK/qtb1SeTRqQT6+oC9ZwsrfaPAfHgvParTOuQ2EuzLd8fBRu/X\r\nxT1yljGEZagXS9tYzyO1vpvtR4od0ix/eYsrRx3CR4t6w+5N07Sti37r+yp/Szz9svVQfPk1Vn3/\r\nAFUHzJtV6iTOeHdkC0Unh0QjYjuCPyDRZ5TEzKuK0HRXvkoIQuN+65F8aewrreRte6MztOD3b7RD\r\nZ8oIU23og5toJgz7pooJPplgXZHDNJKy2oQ6LddaKQy2FWzY71TIvfJUdh2NOiDZbCyzsotKJYeX\r\naG6awVNhqB5RB8EcoAkaHd54jwI1HkqONqFfhadFKFthjIAnM6PFusL/AOR/4PH4jzQqbNdF1ZGl\r\np/XAjQrbuZohWfjBwIIBHYdVV2jrnuth8Yx/EsmNzNrgjTUfFAZ5g42j+1OjYJJiO6fqnh5Hksnm\r\nwviduyNLT38x2jtCXCjoOzpp0qOIFgTXp6fipGnRDBKreJMDoePI9n9E9ZRoz1fJYNirHhytEMIu\r\nAsDQeYH9PzVCcki/Ac0TwIwaBfo4VX9/1qiypbBxTjho1/Q2Yn3oviGH0Lh+KJTiig/Qsi5TyDWj\r\n/kfyRWZ9uV1/QczxD/Yl+39IssqlxNY3RJMyZcHgdJu6pCFzdTMCMkVJyduJtKsBZHwyEcDXL0Ni\r\n/MD0XsPQnpS2Vu6XU4VoTXVFD8XE+C8atXNn5bo3hzTR4adnNIvoVscEyfTGO/eAKmAWc6GbUE+L\r\nG+7NOBPaWmjff+S0i83dU4SwzRCWUMH69VHPHvNc36wLfUEJ9rlpOcMZg8Qe+hSGzO6yI7W6ssre\r\nySQejyEJJty9XysnOawaTYwJpahreqgewYuqFp4o9El15AlDJncxlG0/FyaVjacdINv0UhNxkDDM\r\nWFct+8EAyGUbR3HG8FBmY18kUm3uHZuiHZs+oRn3VhZ7GG68LWbOZvBVW87GfJm9pYXOlS2bJRor\r\nc5eAC3gsTtLGMb7HBNnWTJqtnz6ImxyyGzcvvR/HybpHWaIIOtOirZITopNFHkPT8j0CJRqo8rCj\r\nmbuSNDm9/Ed4PEHwTMqSimw5PahJnDMftvodLFb4LlZx3fptrXVv0x4eizXvTfD00+C9nhmB4Kht\r\nbo1j5Nuc3cf9duhP8Q4O+/vVuHsbKtRj6vueeYc4e2iNR6+vYrkWg7OSj2nsOTEkF9ZjjTXjge49\r\nhVqNhsEUbAq9RbtB52s0nh4O3p8Tj1Lc1/Q+Itikd9ZwA790a15uRStVYZjtjY1jdA0AD8Sq7Har\r\nQlhYPPW2+ba5+4Qhj0SU0J0SREPnophUp5qPdTjMNJScOSlpdEamCZK+6nbqm3NP1+uRSEarpLye\r\nl+yTPAEkJOocXtH7rtwem8L/AJivU2nQL5y2FtM4s7JhwB6w7WE9b4C/EBfQ2HMHNFG7F322NFyf\r\nEKt8+4cJYZO4KMp7yo7XDlE1JniPSE/5ib/dl/7uQlnFFukQ/wAxP/uyf9yhUQ1XqI/Qvg58uTdd\r\nHm20LSsFBZrYJpoWkadE6PA1ArakdrP5MdLVTxbyF5eIs9sNwJxI9knkURyItELx+qaRiN+8Elew\r\nlsz+0YqNhGej2RaobSj4qls3ILHUqraUxDN+XAhZXpDjDVFMfOsKjtd+81a5STiCZHGcWmkZwpdQ\r\nhc0NFXNnG3BZoPfBorZssU6J0wTcLgrEo0W1I1JmYzOJVeN2qLYuG2acMe4tZTnPcKtrWNLiRenE\r\nAeaWFsQOMRdLuCUbw6hfuNIc4b5to3t1t+atVt7oXKSTI8cK2yWlNibNDhEWSt3ZXODCR81rSTcl\r\nHqu3Wk7vOq05J2M0jfYT7unuMr3xFpYzi4RsBc3wJPEDwYq5F+ZEq5MbJWljxbTxH4jsI7VncDY7\r\nhNGw/Rdd9rWG789PVbdmyY217x7rfLHFGIy0WHNDnPdvtsbodqNPmlNbjV1g5rmgua1wB3nftCxg\r\nawWSXFrjXAbvHgk2aeU2madLr/IU0u6+z9xkzlTYdVbIHu3ve/cpriG7hc4nf92wVY3bdy10BUcm\r\nG5g3i5vzGOIBJ6z37nu7qi4USTw0KJ1y9jNGyJfhdokuwN0XEJpyeAtKcY9UklqisoysaY0+0klG\r\nsEGOXbXUlRDhcvYvZltkzY+442+M7hPaOLfgQPJJJZdVFSreS0bN5XN5JJeWs2ZshweG7Qk3nvcf\r\npOc71cT+KpR8VxJen7GCRtNhu4LStd1UkkcOBiOQm1FkM0SSQTCfAFyxRtWcaYriSx53Mc36hZbb\r\nQbJZRtJJSYplrBnJNItubwSST6N1uFHgo5OCqONHuvCSSu2KT2DXJq8KTQK3K7RJJPi9jVEzeRIQ\r\n4lpIOosGtCRY8NAomPeSHbxsCgdLqqq+NVpS4kiVklsmDKEW8tF2GLQanTUUao1Viq1rS1bihB4l\r\nx0r5x0B1IrhRSSU82fuyeXD2ROMUcN59a6b7ufHneqkOzhVsJa4VRNuA3TYG7dULNdlpJIfOsTzl\r\ngeXF7YK7sMNFbz7oWd46ltkGuWpJ7rUcUdkAueQCDRcSNDY4rqSvzZvuxsa4eyNFCzRJJJQcf//Z\r\n--00000000000027fdc7057d257064--\r\n`

**Comment by HZSamir** [comment]
+1

**Comment by vitalragaz** [comment]
You can convert the mailpart of the text to a buffer and than to an ASCII string. As example: 

```js
imaps.connect(config).then(function (connection) {
    return connection.openBox('INBOX').then(function () {
        var searchCriteria = [
            '1:5'
        ];
        var fetchOptions = {
            bodies: ['HEADER', 'TEXT'],
        };
        return connection.search(searchCriteria, fetchOptions).then(function (messages) {
            messages.forEach(function (item) {
                var all = _.find(item.parts, { "which": "TEXT" })
                var html = (Buffer.from(all.body, 'base64').toString('ascii'));
                console.log(html)
            });
        });
    });
});
```

**EDIT:**

A more friendly way is by using simpleparser from nodemailer/mailparser:

```js
imaps.connect(config).then(function (connection) {
    return connection.openBox('INBOX').then(function () {
        var searchCriteria = [
            '1:5'
        ];
        var fetchOptions = {
            bodies: ['HEADER', 'TEXT', ''],
        };
        return connection.search(searchCriteria, fetchOptions).then(function (messages) {
            messages.forEach(function (item) {
                var all = _.find(item.parts, { "which": "" })
                var id = item.attributes.uid;
                var idHeader = "Imap-Id: "+id+"\r\n";
                simpleParser(idHeader+all.body, (err, mail) => {
                    console.log(mail.subject)
                    console.log(mail.html)
                    ....
                });
            });
        });
    });
});
```

**Comment by walrus781** [comment]
I have similar issue, but in html object i have false, any advices, pls, i'm really stucked on this :(

**Comment by dropofwill** [comment]
Probably a little late for @walrus781 , but for anyone else that stumbles upon this.

I had the same issue with `html: false`, but it was because I didn't notice that you need to include `''` in the list of bodies (e.g. `bodies: ['HEADER', 'TEXT', '']`). So basically all that was sent to the parser was the id header + undefined.

**Comment by UnKnoWn-Consortium** [comment]
@dropofwill Actually you can even drop `"HEADER"` and `"TEXT"` from the criteria if you are going to let Mailparser do the job as `""` means getting the the entire message (header + body)  in `node-imap`.
