### ISSUE TITLE
Delete and Expunge Feature

### ISSUE THREAD

**Issue by synox** [chadxz/imap-simple#58]
I would like to implement `delete(uids)` as a convenience function to `addFlags(uids, '\\Deleted')`
Moreover I would expose the `expunge()` function. 

Any tips what to look out for? Can I start?

I am using this in my new application (https://github.com/synox/void-mail). So far i just use connection.imap to access the underlying implementation, but this is not clean. 👍

**Comment by chadxz** [comment]
Hey @synox, thanks for reaching out.

I would expect a method named "delete" to actually delete the messages with the specified uids, without having to call a second expunge() method. Don't you think?

If you are wanting to expose a delete() method, wouldn't it be better to do both addFlags and expunge in the same call?

**Comment by synox** [comment]
You are right, i'll do that. :)

**Comment by Felipedelima123** [comment]
Hey guys, thanks for this lib, it really help me. There is any way of use this on fetchOptions? Like:

```
const fetchOptions = {
            bodies: ['HEADER', 'TEXT'],
            markSeen: true,
            markDeleted: true,
        };
```

**Comment by synox** [comment]
I think we could merge this?
