### ISSUE TITLE
Sort mail by decending 

### ISSUE THREAD

**Issue by tecnodev** [chadxz/imap-simple#68]
I'm fetching emails by offset. the results not ordered in DateTime. i tried `sort() `but it throws "`Sort() not a function`" .here my code

```
 var searchCriteria = [`${from}:${to}`];

                var fetchOptions = {
                  bodies: [""],
                  markSeen: false
                };

                let results = await connection.sort(['-ARRIVAL']
                  searchCriteria,
                  fetchOptions
                );
```

**Comment by melitus** [comment]
You can try this
```const searchCriteria = [`${flags}`, ["SINCE", `${from}`], ["BEFORE", `${to}`],["SUBJECT",`${subject}`]] ```

**Comment by ghost** [comment]
Or, you can parse your emails into structured data in an array, then sort them yourself.
