### ISSUE TITLE
Support "Content-Transfer-Encoding: 8bits" (with that "s")

### ISSUE THREAD

**Issue by aurium** [chadxz/imap-simple#70]
I'm receiving e-mails with "Content-Transfer-Encoding: 8bits" text parts. I believe this plural is off standard, but i cant ask this people tu use a correct mailer.

Example:
```
...
---------081020194631--39146b0236ab21b1d099eb6f1f767307
Content-Transfer-Encoding: 8bits
Content-Type: text/html; charset="utf-8"

<html><head>
...
```

**Comment by glensc** [comment]
I think proper would be to modify the raw body before the parsing. and doing so using events.

It's a difficult task as likely need to add an event system where it doesn't exist.

So perhaps it's easier just patch source code locally as done in https://github.com/chadxz/imap-simple/pull/71

**Comment by aurium** [comment]
Yeah...
So... Is @chadxz maintaining it?

**Comment by chadxz** [comment]
No, this repository is no longer maintained. I have published the last version, v6, which has a deprecation indicating as much, the README has been updated, and this repository is being archived.
